{
  "hash": "2755e1e7cf2caf38aa9cf4c7754137de",
  "result": {
    "markdown": "---\ntitle: \"Project 2: Spatial and Temporal Interactive App of Cat Movement\"\nsubtitle: \"Proposal\"\nauthors: \"Sydney Stitt\"\nformat: html\neditor: visual\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(sf)\nlibrary(tmap)\nlibrary(shiny)\nlibrary(lubridate)\n```\n:::\n\n\n## Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## read data \ncat_movement <- read_csv(\"data/cats_us.csv\")\ncat_reference <- read_csv(\"data/cats_us_reference.csv\")\nprint(dim(cat_movement))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 659770     15\n```\n:::\n\n```{.r .cell-code}\nprint(dim(cat_reference))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 154  21\n```\n:::\n\n```{.r .cell-code}\nsave(cat_movement, file = \"cat_movement.RData\")\nsave(cat_reference, file = \"cat_reference.RData\")\n```\n:::\n\n\n## Reason for Choosing this Dataset\n\n**Goals and Motivation:**\n\nI am curious in exploring what variables (such as age, diet, hunting, hours spent indoors, or sex) affect a cat's decision to travel far outside. I have had cats all my life, and my cat loves to go on walks inside. I am personally curious to see if similar cats to him (young male cats) also like to go outside and explore. The goal of this project is to create a spatial temporal interactive map of cat movement and identify any variables that may impact a cat movement.\n\n**Data Information:**\n\nI am using two TidyTuesday datasets collected by volunteer cat owners in the United States for zoologists Roland Kays et al.'s study from 2013 to 2017. Kays et al. published this data in their 2020 paper studying the ecological impacts and outdoor ranges of pet cats (cited below). Cat owners collected data via collar GPS on their cats as they explored outside. The dataset cat_movement has observations of individual cat's longitude and latitude as well as time stamps for their movements collected from 2013 to 2016. cat_movement has 659770 observations across 15 variables, each observation representing a sensor movement detected by the cat's GPS. The dataset cat_reference has data on the 154 American cats that were tracked, with 154 observations representing each individual cat across 21 variables such as sex, age, diet, and time spent indoors.\n\n**Paper/Data Citation:**\n\nKays R, Dunn RR, Parsons AW, Mcdonald B, Perkins T, Powers S, Shell L, McDonald JL, Cole H, Kikillus H, Woods L, Tindle H, Roetman P (2020) The small home ranges and large local ecological impacts of pet cats. Animal Conservation. [doi:10.1111/acv.12563](http://dx.doi.org/10.1111/acv.12563)\n\n## Questions and Analysis Plan\n\n**I plan to address the following questions with my project:**\n\n1.  Do younger cats tend to travel longer distances and spend more time outside than older cats?\n2.  Do cats travel in patterns or \"seemingly\" randomly (based on environmental stimulus or reactions)?\n\n**Analysis Plan:**\n\n*Week 4 (4/8 - 4/14)* Clean data and tidy observations with tidyverse, dplyr, and readr. I will need to specifically separate the date and time observations using lubridate. Merge the reference and movement data together, or determine if the project can be done with the datasets separate. Conduct peer review of another group's project proposal.\n\n*Week 5 (4/15 - 4/21)* Incorporate proposal feedback into a reformed proposal. Start working on practice static graphs to help visualize what the final model will look like with ggplot2, sf, or tmap packages. Start on a shiny app to create an interactive map using the shiny package. Create summary statistics to help contextualize the map using dplyr, or create a function within the app to interactively generate summary statistics.\n\n*Week 6 (4/22 - 4/26)* Clean up the app. Present the project with a Quarto presentation! Get preliminary feedback from Adrien.\n\n*Week 7-8 (4/27 - 5/9)* Incorporate Adrien's feedback and submit the final writeup. Tidy the website.\n\n**Project Organization:**\n\nThe repository is organized by the following folders and files\n\n-   `/data/*`: Data folder\n\n    -   `f/data/*cat_movement.RData`: Cat movement data in rda format\n\n    -   `f/data/*cat_reference.RData`: Cat reference data in rda format\n\n    -   `f/data/*cat_movement.csv`: Cat movement data in csv format\n\n    -   `f/data/*cat_reference.csv`: Cat reference data in csv format\n\n    -   `/data/README.md`: Metadata about the datasets (to be edited after data wrangling)\n\n-   `index.qmd`: The project write-up (to be completed)\n\n-   `proposal.qmd`: The project proposal (to be revised after peer feedback)\n\n-   `presentation.qmd`: The project presentation (to be completed)\n\n-   `_quarto.yml`: Setup file for project website\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}